### ISSUE TITLE
gtsam用的什么版本

### ISSUE THREAD

**Issue by XidianLemon** [XiaotaoGuo/modular_mapping_and_localization_framework#1]
可以留个联系方式吗，最近在学习您的代码。

**Comment by XiaotaoGuo** [comment]
gtsam 的版本可以在 third_party_libs 看哈，联系方式的话你可以留一个邮箱吗？

**Comment by XidianLemon** [comment]
> gtsam 的版本可以在 third_party_libs 看哈，联系方式的话你可以留一个邮箱吗？

看到了，4.1.1版本。现在编译通过，但运行时候报eigen的错误。
好的邮箱是：576852860@qq.com
我的微信号是：15529333055，要是可以加个微信就最好了^_^
