### ISSUE TITLE
eigen报错

### ISSUE THREAD

**Issue by w8128835** [XiaotaoGuo/modular_mapping_and_localization_framework#2]
![image](https://user-images.githubusercontent.com/31956796/226163168-b40ef5ea-134c-40e8-8c82-d61f7177d1f9.png)
 @XiaotaoGuo 您好，我尝试运行您写的这段代码，使用的是ubuntu20.04,按照您readme里面提示的分支安装了所有依赖。但是报上面这幅图的错误，运行时把config文件夹所有的yaml文件都读取了;目前eigen版本是系统自带的3.3.7,如下图，请问您这个怎么能正确运行呢
![image](https://user-images.githubusercontent.com/31956796/226163343-17a1aacc-534b-4654-b9e0-a6a9391b1b1e.png)

**Comment by XiaotaoGuo** [comment]
这个是节点刚起来的时候就报错吗，还是播包的时候才报错呢？另外可以看一下报错信息里面的网址哈

**Comment by w8128835** [comment]
> 

您好，是节点刚起来的时候报错，后来发现是编译选项的问题，已经解决了，非常感谢～
